new extended Version of simulator 2.x flow
openWB/tools pull request #12
Opened 2023-09-28 12:13 UTC by Magnus8513

This extended Version of the simulator flow extends the capability to build more complex environments with cascading EVUs

2023-09-29 08:02 UTC, benderl commented
@Magnus8513
Kannst Du bitte die .DS_Store Dateien entfernen?

2023-09-29 08:34 UTC, Magnus8513 commented
> @Magnus8513 Kannst Du bitte die .DS_Store Dateien entfernen?

klar - ist weg jetzt weg und sollte da natürlich gar nicht hin. Habt Ihr Euch überlegt ob wir das erweiterte JSON erstmal "additiv" als option daneben pflegen wollen statt das bestehende komplett zu ersetzten?

2023-09-29 09:16 UTC, Magnus8513 commented
nochmal ein paar Kleinigkeiten aufgeräumt und es erstmal separiert in einem einzelnen Ordner.

2023-10-12 05:42 UTC, benderl commented
@Magnus8513 
Kann der erweiterte Flow parallel zum bestehenden in Node-Red installiert werden? Ich denke, es kommt zu Konflikten mit den Subflows und möchte mir meinen bestehenden Simulator nicht zerschießen.

2023-10-12 05:52 UTC, benderl requested changes

2023-10-12 05:52 UTC, benderl commented on .gitignore
> +Simulator 2.x/extended version/.DS_Store
```suggestion
.DS_Store
```
Die Zeile ist ausreichend. Wird nur ein Dateiname angegeben, dann wird der in sämtlichen Verzeichnissen ausgeschlossen.

2023-10-12 05:52 UTC, benderl commented on Simulator 2.x/README.md
> +
```suggestion
```
Es macht keinen Sinn, für eine simple Konfiguration ein komplettes Backup bereitzustellen. Der größte Nachteil ist, dass der Softwarestand schnell veraltet ist und regelmäßig aktualisiert werden müsste.

Besser eine eigene `README.md` in dem neuen Verzeichnis anlegen und mit ein paar Screenshots die notwendigen Einstellungen erläutern.

2025-04-17 06:34 UTC, closed without merging